In [1]:
import torch
import numpy as np

In [2]:
# Initialize a tensor directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
# Initialize a tensor directly from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
# Initialize a tensor directly from another tensor
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)  # new tensors retains the properties (shape, datatype) of the argument tensor, unless explicity overridden
print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1803, 0.4998],
        [0.0880, 0.4683]])


In [5]:
# Initialize a tensor with random or constant values
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [6]:
# Attributes of a tensor
tensor = torch.rand(3, 4)
print(f'Shape {tensor.shape}')
print(f'Datatype {tensor.dtype}')
print(f'Device {tensor.device}')

Shape torch.Size([3, 4])
Datatype torch.float32
Device cpu


In [7]:
# Move to mps
if torch.backends.mps.is_available():
    tensor = tensor.to('mps')
print(tensor.device)

mps:0


In [8]:
# Indexing and slicing
tensor = torch.rand(4, 4)
print(f'Original tensor {tensor}')
print(f'First column {tensor[:, 0]}')
print(f'Last column {tensor[:, -1]}')
tensor[:, 1] = 0
print(f'Changed tensor {tensor}')

Original tensor tensor([[0.6004, 0.3708, 0.6699, 0.5397],
        [0.6660, 0.1220, 0.9896, 0.5484],
        [0.9025, 0.0991, 0.4507, 0.3666],
        [0.3187, 0.2950, 0.0390, 0.3503]])
First column tensor([0.6004, 0.6660, 0.9025, 0.3187])
Last column tensor([0.5397, 0.5484, 0.3666, 0.3503])
Changed tensor tensor([[0.6004, 0.0000, 0.6699, 0.5397],
        [0.6660, 0.0000, 0.9896, 0.5484],
        [0.9025, 0.0000, 0.4507, 0.3666],
        [0.3187, 0.0000, 0.0390, 0.3503]])


In [9]:
# Concatenate
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.6004, 0.0000, 0.6699, 0.5397, 0.6004, 0.0000, 0.6699, 0.5397, 0.6004,
         0.0000, 0.6699, 0.5397],
        [0.6660, 0.0000, 0.9896, 0.5484, 0.6660, 0.0000, 0.9896, 0.5484, 0.6660,
         0.0000, 0.9896, 0.5484],
        [0.9025, 0.0000, 0.4507, 0.3666, 0.9025, 0.0000, 0.4507, 0.3666, 0.9025,
         0.0000, 0.4507, 0.3666],
        [0.3187, 0.0000, 0.0390, 0.3503, 0.3187, 0.0000, 0.0390, 0.3503, 0.3187,
         0.0000, 0.0390, 0.3503]])


In [10]:
# Arithmetic operations
# Matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1, y2, y3)

# Element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1, z2, z3)

tensor([[1.1005, 1.3587, 1.0416, 0.4066],
        [1.3587, 1.7235, 1.2481, 0.4430],
        [1.0416, 1.2481, 1.1520, 0.4337],
        [0.4066, 0.4430, 0.4337, 0.2259]]) tensor([[1.1005, 1.3587, 1.0416, 0.4066],
        [1.3587, 1.7235, 1.2481, 0.4430],
        [1.0416, 1.2481, 1.1520, 0.4337],
        [0.4066, 0.4430, 0.4337, 0.2259]]) tensor([[1.1005, 1.3587, 1.0416, 0.4066],
        [1.3587, 1.7235, 1.2481, 0.4430],
        [1.0416, 1.2481, 1.1520, 0.4337],
        [0.4066, 0.4430, 0.4337, 0.2259]])
tensor([[0.3605, 0.0000, 0.4488, 0.2912],
        [0.4436, 0.0000, 0.9793, 0.3007],
        [0.8145, 0.0000, 0.2031, 0.1344],
        [0.1016, 0.0000, 0.0015, 0.1227]]) tensor([[0.3605, 0.0000, 0.4488, 0.2912],
        [0.4436, 0.0000, 0.9793, 0.3007],
        [0.8145, 0.0000, 0.2031, 0.1344],
        [0.1016, 0.0000, 0.0015, 0.1227]]) tensor([[0.3605, 0.0000, 0.4488, 0.2912],
        [0.4436, 0.0000, 0.9793, 0.3007],
        [0.8145, 0.0000, 0.2031, 0.1344],
        [0.1016, 0.0000, 0.00

In [11]:
# Convert to Python numerical value
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

6.4417266845703125 <class 'float'>


In [12]:
# In-place operation (suffix "_")
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[0.6004, 0.0000, 0.6699, 0.5397],
        [0.6660, 0.0000, 0.9896, 0.5484],
        [0.9025, 0.0000, 0.4507, 0.3666],
        [0.3187, 0.0000, 0.0390, 0.3503]])
tensor([[5.6004, 5.0000, 5.6699, 5.5397],
        [5.6660, 5.0000, 5.9896, 5.5484],
        [5.9025, 5.0000, 5.4507, 5.3666],
        [5.3187, 5.0000, 5.0390, 5.3503]])


In [14]:
# Tensor to numpy
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [15]:
# Numpy to tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f'n: {n}')
print(f't: {t}')

n: [2. 2. 2. 2. 2.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
